%STEP 3 - Demo created for PCOMS MODEL RESULTS
% Author: ISABELLA ASCIONE
% email: isabellascione@gmail.com
% this script provides examples on how to generate images
% for 
clear all
addpath export_fig
% DEFINE INPUT FILES HERE:
% PointsMatrixFile is the file generated using the preprocessing script
% named STEP1.m . See this script for additional information 
PointsMatrixFile='pcoms\PointsMatrix.dat';
% BoxStructureFile is the file generated by the preprocessing script named 
% STEP2.m .  See this script for additional information 
BoxStructureFile='pcoms\Box.mat';
% fluxes_file is the name of the fluxes timeseries file generated by MOHID 
% consult mohid wiki about how to generate this file from MOHID run
% 
fluxes_file='pcoms\with rivers\nitrate.BXF';
% Coastline file is the file representing the coastline. this file is
% organized in two columns with vertices of polygons representing land. 
% Each polygon is identified by a starting line and an ending line with
% "nan nan". 
%
Coastline=load('pcoms\XY.dat'); 
% In the case of Portugal the coastline file resulted to be too heavy to load in the matlab figure,
% and for this reason it was reduced in resolution by using a step of 200
% points. If your coastline is a small file, use step=1.
step=200;
Coastline=[Coastline(1,:);Coastline(2:step:end-1,:);Coastline(end,:)];
% arrow_width is the size of the arrows . It is a parameter to be changed
% by trial and errors. In the case of the Portuguese Coast model the value
% arrow_width=0.013 was used for horizontal arrows
% arrow_width=0.0091 was used for vertical arrows (see Example 6 below)
arrow_width=0.013;
%provide geographic limits to display figure:
minlon=-11; % Longitude degrees
maxlon=-3.298; % Longitude degrees
minlat=35; % Latitude Degrees
maxlat=45; % Latitude Degrees
figure_axis=[minlon maxlon minlat maxlat];
% Define the color of the coastline (in this case it is grey)
color_coastline=[0.8 0.8 0.8];

% Define total number of vertical layers + 1. This is just used to draw the
% coastline on the top of all the boxes.
TotNumLayers=51;

PointsMatrix=load(PointsMatrixFile);

load(BoxStructureFile);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 1: draw boxes without numbers, fluxes, and coastline
figure(1)

figure_name='Boxes_map';
% This example was made for the Portuguese Coast, where there are five
% vertical layers of boxes, and a total of 40 boxes (plus box 0)
% Boxnum contains the numbers of all the boxes
Boxnum=1:40;
n=length(Boxnum);
for i=1:n;h1(i)=DrawBox(Box,Boxnum(i),'VerticalZ','depth','color','variable');end;
axis(figure_axis);
title('Pcoms Boxes')
xlabel('longitude')
ylabel('latitude')
%zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
export_fig(figure_name,'-png','-nocrop');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 2: draw surface boxes, nitrate fluxes, and coastline 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; clear h1;
figure(2)
figure_name='surface_boxes_nitrate';
fluxes_file='D:\Aplica\Software\BVT_update\Data\NitrateFluxes_CompliantJanFev2010.dat'
% Read the fluxes from MOHID file. 1e6 is the conversion coefficient to convert fluxes
% to million tons
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
% In this Example, we draw only surface boxes. In the case of the Portuguese Coast 
% there are five vertical layers of boxes, and a total of 40 boxes, plus
% box 0. In MOHID, each vertical stack of boxes is numbered from surface to
% bottom. 
% This means that in the case of the Portuguese Coast, 
% surface boxes will have the following numbers:
% boxes have the following numbers:
% 1     6    11    16    21    26    31    36
% the layer of boxes below the surface will have the numbers:
% 2     7    12    17    22    27    32    37
% and so on...
% Following this, the surface boxes can be defined by the array Boxnum as:
Boxnum=1:5:40;
n=length(Boxnum);
% The following instructions are a loop across the box numbers. 
% The function DrawBox is drawing each box, provided the structure Box and
% the number of the Box to draw:
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
% The function Drawflux is drawing the arrows between the boxes
DrawFlux(Box,[0 Boxnum],TableOfFluxes,arrow_width,'ontop');
axis(figure_axis);
view(2)
title('Nitrate Residual Fluxes Mar 2012-Apr 2012','fontsize',13)
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid on
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
axis([-10.4433   -6.2092   35.7750   44.9005]);

export_fig(figure_name,'-png','-nocrop');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 3: draw surface boxes, phytoplankton fluxes, and coastline 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; 
figure_name='surface_boxes_phytoplankton';
fluxes_file='pcoms\no rivers\phytoplankton.BXF'
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
Boxnum=1:5:40;
n=length(Boxnum);
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
DrawFlux(Box,[0 Boxnum],TableOfFluxes,arrow_width,'ontop');
axis(figure_axis);
view(2)
title('Phytoplankton Residual Fluxes - Mar 2012-Apr 2012','fontsize',13)
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid on
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
axis([-10.4433   -6.2092   35.7750   44.9005]);

export_fig(figure_name,'-png','-nocrop');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 4: draw surface boxes, phosphorus fluxes, and coastline 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; clear h2;
figure_name='surface_boxes_phosphorus';
fluxes_file='pcoms\no rivers\inorganic phosphorus.BXF';
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
Boxnum=1:5:40;
n=length(Boxnum);
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
DrawFlux(Box,[0 Boxnum],TableOfFluxes,arrow_width,'ontop');
axis(figure_axis);
view(2)
title('Phosphate Residual Fluxes - Mar 2012-Apr 2012','fontsize',13)
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid on
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
axis([-10.4433   -6.2092   35.7750   44.9005]);
export_fig(figure_name,'-png','-nocrop');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 5:  water fluxes, and coastline 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; clear h2;
fluxes_file='pcoms\no rivers\water.BXF'
figure_name='boxes_water';
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
Boxnum=1:5:40;
n=length(Boxnum);
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
DrawFlux(Box,[0 Boxnum],TableOfFluxes,arrow_width,'ontop');
axis(figure_axis);
view(2)
title('Water Residual Fluxes - Mar 2012-Apr 2012','fontsize',13)
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid on
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
axis([-10.4433   -6.2092   35.7750   44.9005]);
export_fig(figure_name,'-png','-nocrop');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 6:  VERTICAL FLUXES
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; clear h2;
fluxes_file='pcoms\with rivers\nitrate.BXF';
arrow_width=0.0091;
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
Boxnum=1:40;
n=length(Boxnum);
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
hold on
for i=1:5:40
DrawFlux(Box,[i:i+4],TableOfFluxes,arrow_width,'default');
end
axis(figure_axis);
view(2)
title('Nitrate vertical fluxes - Mar 2012-Apr 2012','fontsize',13)
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid on
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
view(-91,40);
axis([-10.4433   -6.2092   35.7750   44.9005   20.0000   55.0000])
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%EXAMPLE 6.1: Animation of vertical fluxes
axis off
angles=0:-10:-180;

for i=1:length(angles);
    view(angles(i),40);name=cat(2,'NITRATE_RIV_',num2str(i));
    export_fig(name,'-png','-nocrop');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 7:  VERTICAL FLUXES
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; clear h2;
fluxes_file='pcoms\with rivers\inorganic phosphorus.BXF'
arrow_width=0.0091;
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
Boxnum=1:40;
n=length(Boxnum);
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
hold on
for i=1:5:40
DrawFlux(Box,[i:i+4],TableOfFluxes,arrow_width,'default');
end
axis(figure_axis);
view(2)
title('Phosphate vertical fluxes - Mar 2012-Apr 2012','fontsize',12,'fontweight','bold')
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid on
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
view(-91,40);
axis([-10.4433   -6.2092   35.7750   44.9005   20.0000   55.0000])
grid off
axis off
angles=0:-10:-180;
for i=1:length(angles);view(angles(i),40);
    name=cat(2,'PHOSPHATE_RIV_',num2str(i))
    export_fig(name,'-png','-nocrop');
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 8:  VERTICAL FLUXES (water)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; clear h2;
fluxes_file='pcoms\with rivers\water.BXF'
arrow_width=0.0091;
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
Boxnum=1:40;
n=length(Boxnum);
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
hold on
for i=1:5:40
DrawFlux(Box,[i:i+4],TableOfFluxes,arrow_width,'default');
end
axis(figure_axis);
view(2)
title('Water vertical fluxes - Mar 2012-Apr 2012','fontsize',12,'fontweight','bold')
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid off
axis off
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
view(-91,40);

axis([-10.4433   -6.2092   35.7750   44.9005   20.0000   55.0000])
for i=1:length(angles);view(angles(i),40);
    name=cat(2,'WATER_RIV_',num2str(i)); 
    export_fig(name,'-png','-nocrop');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Example 9:  VERTICAL FLUXES (Phytoplankton)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clf; clear h2;

fluxes_file='pcoms\with rivers\phytoplankton.BXF'
arrow_width=0.011;
[TableOfFluxes]=ReadResidualFlux(fluxes_file,1e6);
Boxnum=1:40;
n=length(Boxnum);
for i=1:n;h2(i)=DrawBox(Box,Boxnum(i));end;
hold on
for i=1:5:40
DrawFlux(Box,[i:i+4],TableOfFluxes,arrow_width,'default');
end
axis(figure_axis);
view(2)
title('Phytoplankton vertical fluxes - Mar 2012-Apr 2012','fontsize',12,'fontweight','bold')
xlabel('longitude','fontsize',12)
ylabel('latitude','fontsize',12)
zlabel('layers')
hold on
patchcoastline(Coastline,color_coastline,TotNumLayers);
grid off
axis off
set(gca,'Linewidth',2,'fontsize',12)
set(gcf,'color','white')
view(-91,40);
axis([-10.4433   -6.2092   35.7750   44.9005   20.0000   55.0000])
for i=1:length(angles);view(angles(i),40);;name=cat(2,'PHYTO_RIV_',num2str(i)); export_fig(name,'-png','-nocrop');;end


 